export enum ListLabels {
  owners = 'Owners',
  mediatypes2 = 'Media Types',
  mediatypes3 = 'Media Types',
  mediatypes5 = 'Media Types',
  categories = 'Categories',
  diversetargets = 'Diverse Target',
  languages2 = 'Language',
  markets = 'Markets',
  dmas = "DMA",
  msas = "MSA",
  tvbands = 'Bands',
  tvnetworks = 'Networks',
  dmamarkets = 'Markets (DMA)',
  languages = 'Language',
  types = 'Types',
  subTypes = 'Subtypes',
  networks = 'Networks',
  bands = 'Bands',
  owners11 = 'Owners',
  owners3 = 'Owners',
  owners5 = 'Owners',
  radiobands = 'Bands',
  formats = 'Formats'
};

export enum ListKeys {
  owners = 'owners',
  mediatypes2 = 'mediatypes2',
  mediatypes3 = 'mediatypes3',
  mediatypes5 = 'mediatypes5',
  types = 'types',
  categories = 'categories',
  diversetargets = 'diversetargets',
  languages2 = 'languages2',
  markets = 'markets',
  dmas = 'dmas',
  msas = 'msas',
  tvbands = 'tvbands',
  tvnetworks = 'tvnetworks',
  dmamarkets = 'dmamarkets',
  languages = 'languages',
  subTypes = 'subTypes',
  networks = 'networks',
  bands = 'bands',
  owners11 = 'owners11',
  owners3 = 'owners3',
  owners5 = 'owners5',
  radiobands = 'radiobands',
  formats = 'formats'
}

export enum ListUrls {
  categories = '/lists/categories/',
  mediatypes2 = '/lists/mediatypes2/',
  mediatypes3 = '/lists/mediatypes/3',
  mediatypes5 = '/lists/mediatypes/5',
  diversetargets = '/lists/diversetargets/',
  languages2 = '/lists/languages2/',
  languages = '/lists/languages/',
  dmas = '/lists/dmas/',
  msas = '/lists/msas/',
  tvbands = '/lists/tvbands/',
  tvnetworks = '/lists/tvnetworks/',
  subTypes = '/lists/subTypes',
  owners = '/lists/owners/',
  owners11 = '/lists/owners/11',
  owners3 = '/lists/owners/3',
  owners5 = '/lists/owners/5',
  radiobands = '/lists/radiobands',
  formats = '/lists/formats'
}
