export enum MediaProfileFields {
  mavenId = 'mavenId',
  id = 'id',
  phone = 'phone',
  workingPhone = 'workingPhone',
  address = 'address',
  website = 'website',
  email = 'email',
  owner = 'owner',
  parent = 'parent',
  type = 'type',
  language = 'language',
  categories = 'categories',
  geographicAppeal = 'geographicAppeal',
  dma = 'dma',
  msa = 'msa',
  slogan = 'slogan',
  class = 'class',
  frequency = 'frequency',
  fccid = 'fccid',
  licenseCity = 'licenseCity',
  licenseCountry = 'licenseCountry',
  timeZone = 'timeZone',
  power = 'power',
  coordinates = 'coordinates',
  certified = 'certified',
  classfied = 'classfied',
  fcc = 'fcc',
  target = 'target',
  files = 'files',
  mediaPartners = 'mediaPartners',
  callHistory = 'callHistory',
  haat = 'haat',
  agl = 'agl',
  amsl = 'amsl',
  displayChannel = "displayChannel",
  digitalChannel = "digitalChannel",
}

export enum MediaProfileFieldsLabels {
  mavenId = 'Maven ID',
  id = 'ID',
  phone = 'Phone',
  workingPhone = 'Working Phone',
  address = 'Address',
  website = 'Website',
  email = 'Email',
  owner = 'Owner',
  parent = 'Parent',
  type = 'Type',
  language = 'Language',
  categories = 'Categories',
  geographicAppeal = 'Geographic Appeal',
  dma = 'DMA',
  msa = 'MSA',
  slogan = 'Slogan',
  class = 'Class',
  frequency = 'Frequency',
  fccid = 'FCCID',
  licenseCity = 'License City',
  licenseCountry = 'License Country',
  timeZone = 'Time Zone',
  power = 'Power',
  coordinates = 'Coordinates',
  certified = 'Certified',
  classfied = 'Classfied',
  fcc = 'FCC',
  target = 'Target',
  files = 'Files',
  mediaPartners = 'Media Partners',
  callHistory = 'Call History',
  haat = 'HAAT',
  agl = 'AGL',
  amsl = 'AMSL',
  displayChannel = "Display Channel",
  digitalChannel = "Digital Channel",
}

export enum FilesLabels {

}
